# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  snyk: snyk/snyk@0.0.9
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: 'circleci/node:4.8.2'
      - image: 'circleci/mongo:4.2'
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Start service
          command: npm start
      - snyk/scan:
          docker-image-name: 'circleci/node:4.8.2'
          monitor-on-build: true
workflows:
  version: 1
  build_and_test:
    jobs:
      - build


