version: 2.1
# Use a package of configuration called an orb.
orbs:
  snyk: snyk/snyk@0.0.9
# Orchestrate or schedule a set of jobs
jobs:
  build:
    working_directory: ~/goof-heroku
    docker:
      - image: 'circleci/node:4.8.2'
      - image: 'circleci/mongo:4.2'
    steps:
      - checkout
      - run:
          name: install npm
          command: npm install  
      - snyk/scan:
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app'
          fail-on-issues: false
          monitor-on-build: true
          token-variable: SNYK_AUTH
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: org-global


