# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  snyk: snyk/snyk@0.0.9
# Orchestrate or schedule a set of jobs
jobs:
  context: org-global
  build:
    working_directory: ~/goof-heroku
    docker:
      - image: 'circleci/node:4.8.2'
      - image: 'circleci/mongo:4.2'
    steps:
      - checkout
      - run:
          name: install npm
          command: npm install
      - run:
          name: enviro variables 
          command: echo ${PRACTICE}     
      - snyk/scan:
          docker-image-name: 'circleci/node:4.8.2'
          fail-on-issues: false
          monitor-on-build: true
          token-variable: ${SNYK_AUTH}
workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: org-global


